#define STARTPROGRAM 1
#define STOPPROGRAM 2
#define WAIT4S 3
#define HOMEMOTOR 4
#define MEMERR 5
#define USERINT 6
#define EXECUTE 7
#define DELETE 8
#define OPENCOMERR 9
#define GPSTIMEOUT 10
#define SETCPUTIME 11
#define USEDCPUTIME 12
#define POWERON 13
#define POWEROFF 14
#define MOVEMOTOROK 15
#define MOTORDONE 16
#define ALREADYHOME 17
#define MOVEMOTOR 18
#define DOSCANDONE 19
#define DOSCANTIMEOUT 20
#define SPECREFUSE 21
#define DONEINITSPEC 22
#define INITSPEC 23
#define WRITEOK 24
#define NOTOK 25
#define CONTACTSPEC 26
#define NOCONTACTSPEC 27
#define SERIALOPEN 28
#define SERIALOPENERR 29
#define COMMAND 30
#define PAUSE 31
#define RESUME 32
